/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlentoursRouteImport } from './routes/alentours'
import { Route as AppartementRouteImport } from './routes/appartement'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ResidenceRouteImport } from './routes/residence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlentoursRoute = AlentoursRouteImport.update({
  id: '/alentours',
  path: '/alentours',
  getParentRoute: () => rootRouteImport,
} as any)
const AppartementRoute = AppartementRouteImport.update({
  id: '/appartement',
  path: '/appartement',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidenceRoute = ResidenceRouteImport.update({
  id: '/residence',
  path: '/residence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alentours': typeof AlentoursRoute
  '/appartement': typeof AppartementRoute
  '/contact': typeof ContactRoute
  '/residence': typeof ResidenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alentours': typeof AlentoursRoute
  '/appartement': typeof AppartementRoute
  '/contact': typeof ContactRoute
  '/residence': typeof ResidenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alentours': typeof AlentoursRoute
  '/appartement': typeof AppartementRoute
  '/contact': typeof ContactRoute
  '/residence': typeof ResidenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alentours' | '/appartement' | '/contact' | '/residence'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alentours' | '/appartement' | '/contact' | '/residence'
  id:
    '__root__' | '/' | '/alentours' | '/appartement' | '/contact' | '/residence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlentoursRoute: typeof AlentoursRoute
  AppartementRoute: typeof AppartementRoute
  ContactRoute: typeof ContactRoute
  ResidenceRoute: typeof ResidenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alentours': {
      id: '/alentours'
      path: '/alentours'
      fullPath: '/alentours'
      preLoaderRoute: typeof AlentoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appartement': {
      id: '/appartement'
      path: '/appartement'
      fullPath: '/appartement'
      preLoaderRoute: typeof AppartementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residence': {
      id: '/residence'
      path: '/residence'
      fullPath: '/residence'
      preLoaderRoute: typeof ResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlentoursRoute: AlentoursRoute,
  AppartementRoute: AppartementRoute,
  ContactRoute: ContactRoute,
  ResidenceRoute: ResidenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
